### ISSUE TITLE
React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by imhazige** [web-ridge/react-native-paper-tabs#3]
When use like this 
```jsx
<TabScreen key={i} label={name}>
            {renderFunc()}
</TabScreen>
```
some times it will throw this error.

**Comment by RichardLindhout** [comment]
This is a restriction in our library because I think it will result in bugs if we remove this restriction.

I guess you are currently returning an array of elements?
[
    <element1 key="1" />
    <element2 key="2"  />
]

In your renderfunc instead of returning an array of elements you could use a <React.Fragment> around your array of elements
```
<React.Fragment>
    <element1 />
    <element2 />
</React.Fragment>
```

 or a shorter version 
 ```
 <>
    <element1 />
    <element2 />
</>
 ```

**Comment by RichardLindhout** [comment]
@imhazige did this fix it for you?

**Comment by imhazige** [comment]
Hi, @RichardLindhout 
renderFunc will return a single root component.

This will work
```jsx
<Tabs>
  <TabScreen>
          <View></View>  
  </TabScreen>
  <TabScreen>
          <View></View>  
  </TabScreen>
</Tabs>

```
but when change to an iteration, it will throw the error.

```jsx
<Tabs>
  {[someaaray].map(({renderFunc})=>{
    return (<TabScreen key={i} label={name}>
                {renderFunc()}
    </TabScreen>);
})}
</Tabs>

```
