### ISSUE TITLE
Keyboard doesn't open when tapping a TextInput inside a TabScreen on iPhone

### ISSUE THREAD

**Issue by farcondee** [web-ridge/react-native-paper-tabs#35]
The keyboard won't open when tapping any `<TextInput>` inside your `<TabScreen>` components. This happens both in the simulator and on my physical device. I even tried updating all relevant libraries: React Native, React Native Paper, Your library, React Native Pager View. Didn't help. This is a pretty major bug completely halting all our development. Would be highly appreciated if anyone could take a look

**Where this bug has been found:**
- iPhone SE (2nd generation) simulator
- iPhone SE (2nd generation) physical device
- iPhone 13 simulator

**Video showing the bug in action:**
[Bug video](https://i.imgur.com/38YwtF8.mp4)

**How to reproduce:**
- On an iPhone SE (simulator or device), add a `<TextInput>` anywhere inside the `<TabScreen>` component
- Tap the input 
- The screen just flickers. It looks like the keyboard begins to slide up but immediately is dismissed

**Expected Behaviour:**
The keyboard should show when tapping a `<TextInput>`

**Current Behaviour:**
The keyboard begins to show but is immediately dismissed, when tapping a `<TextInput>`

**Comment by KazakovVS** [comment]
Have the same issue

**Comment by davram88** [comment]
Same issue, Anyone has a solution?

**Comment by aretesoftware** [comment]
This exact same issue happens for me as well. In my case I'm using @react-navigation/material-top-tabs for tabs instead. Curious enough, the issue doesn't occur until I hit the Tab key. 

I feel like the issue may be better resolved in https://github.com/callstack/react-native-paper, rather than the tab libraries. Please let me know if I'm wrong and there is an issue in react-native-paper-tabs so that I can then convey the fix to material-top-tabs.

Only seems to occur in iOS. Android seems fine.

**Comment by RichardLindhout** [comment]
Could we create a snack for this? I don't have this issue if I remember correctly
