### ISSUE TITLE
Stopped working after upgrade to react native 0.72.1

### ISSUE THREAD

**Issue by lelimit** [web-ridge/react-native-paper-tabs#51]
Changing tab results in: 
Uncaught TypeError TypeError: indicatorRef.current.setNativeProps is not a function
    at <anonymous> (...........\node_modules\react-native-paper-tabs\lib\module\internal.ts:41:34)

**Comment by AlexSirenko** [comment]
I faced the same.

**Comment by AlexSirenko** [comment]
Do you have any workarounds here?

**Comment by RichardLindhout** [comment]
I'm looking into it!

**Comment by RichardLindhout** [comment]
Hi it seems to be working fine for me on latest react-native / expo. It looks like it was added back to Fabric too a while ago.
https://github.com/facebook/react-native/commit/1d3fa40c59b234f21f516db85c322ec0ed0311e0 so it should work again in the future.

Moving away from setNativeProps would mean introducing reanimated on native and a rewrite (which could be good since many have this dependency anyway, but not in the mood for this right now :)

Are you guys using Fabric?

**Comment by RichardLindhout** [comment]
Ah it's only on the web version right? I don't use setNativeProps on native. Hmmm. Looking into it

**Comment by RichardLindhout** [comment]
Works now, I moved away from setNativeProps
